import React, { createContext, useContext, useState } from "react";


const DrugsContext = createContext();


export const DrugsProvider = ({ children }) => {
  const [allDrugs, setAllDrugs] = useState([
    {
      medid: 1,
      medname: "Lipitor",
      brandname: "Pfizer",
      drug_category: "Cardiovascular",
      store_name: "Rite Aid Pharmacy",
      distance: 3.0,
      availability: true,
      home_delivery: true,
      price: 22.0,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "cholesterol reduction",
      alt_meds: "Atorvastatin, Simvastatin",
      rating: 4.5,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dzymyjltu/image/upload/v1731685309/lipitor_quwj3a.jpg",
      description: "Lipitor is a medication used to lower cholesterol and reduce the risk of heart disease."
    },
    {
      medid: 5,
      medname: "Zyrtec",
      brandname: "Johnson & Johnson",
      drug_category: "Antihistamine",
      store_name: "CVS Pharmacy",
      distance: 4.0,
      availability: true,
      home_delivery: true,
      price: 13.00,
      tier: 1,
      generic: false,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "6+ years",
      tags: "allergy relief",
      alt_meds: "Claritin, Allegra",
      rating: 4.7,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690375/download_xm5msx.jpg",
      description: "Zyrtec is an antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes."
    },
    {
      medid: 7,
      medname: "Xanax",
      brandname: "Pfizer",
      drug_category: "Psychiatry",
      store_name: "Walmart Pharmacy",
      distance: 3.0,
      availability: true,
      home_delivery: true,
      price: 28.50,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "0.5mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "anxiety relief",
      alt_meds: "Lorazepam, Clonazepam",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690425/download_gx4fx0.jpg",
      description: "Xanax is used to treat anxiety and panic disorders by calming the nervous system."
    },
    {
      medid: 10,
      medname: "Synthroid",
      brandname: "AbbVie",
      drug_category: "Endocrine",
      store_name: "Rite Aid",
      distance: 4.0,
      availability: true,
      home_delivery: true,
      price: 18.50,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "50mcg",
      days_supply: 30,
      age_range: "12+ years",
      tags: "thyroid hormone replacement",
      alt_meds: "Levothyroxine, Euthyrox",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690060/download_mmm4ay.jpg",
      description: "Synthroid is used to treat hypothyroidism (low thyroid hormone levels) by providing synthetic thyroid hormone."
    },
    {
      medid: 2,
      medname: "Lipitor",
      brandname: "Pfizer",
      drug_category: "Cardiovascular",
      store_name: "Walgreens",
      distance: 1.5,
      availability: true,
      home_delivery: true,
      price: 28.0,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "cholesterol reduction",
      alt_meds: "Atorvastatin, Simvastatin",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dzymyjltu/image/upload/v1731685309/lipitor_quwj3a.jpg",
      description: "Lipitor is a medication used to lower cholesterol and reduce the risk of heart disease."
    },
    
    {
      medid: 13,
      medname: "Amoxicillin",
      brandname: "Mylan",
      drug_category: "Antibiotic",
      store_name: "Walgreens Pharmacy",
      distance: 2.0,
      availability: true,
      home_delivery: true,
      price: 14.50,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "500mg",
      days_supply: 10,
      age_range: "All ages",
      tags: "bacterial infections",
      alt_meds: "Penicillin, Cephalexin",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690099/download_n2zalx.jpg",
      description: "Amoxicillin is an antibiotic used to treat various bacterial infections such as ear infections, pneumonia, and strep throat."
    },
    {
      medid: 16,
      medname: "Metformin",
      brandname: "Bristol-Myers Squibb",
      drug_category: "Antidiabetic",
      store_name: "Walgreens Pharmacy",
      distance: 1.5,
      availability: true,
      home_delivery: true,
      price: 9.50,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "500mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "diabetes management",
      alt_meds: "Glipizide, Glyburide",
      rating: 4.9,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690236/download_saqb5g.jpg",
      description: "Metformin is used to manage blood sugar levels in people with type 2 diabetes and helps improve insulin sensitivity."
    },
    {
      medid: 19,
      medname: "Albuterol",
      brandname: "Ventolin",
      drug_category: "Respiratory",
      store_name: "Walgreens Pharmacy",
      distance: 1.2,
      availability: true,
      home_delivery: true,
      price: 36.00,
      tier: 2,
      generic: true,
      dosage_form: "inhaler",
      strength: "90mcg",
      days_supply: 30,
      age_range: "4+ years",
      tags: "asthma relief, bronchospasm",
      alt_meds: "Levalbuterol, Terbutaline",
      rating: 4.8,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690273/download_zkqrot.jpg",
      description: "Albuterol is a bronchodilator used to relieve bronchospasm in people with asthma and chronic obstructive pulmonary disease (COPD)."
    },
    {
      medid: 22,
      medname: "Gabapentin",
      brandname: "Neurontin",
      drug_category: "Neurology",
      store_name: "Walgreens Pharmacy",
      distance: 3.5,
      availability: true,
      home_delivery: false,
      price: 16.00,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "300mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "nerve pain, seizures",
      alt_meds: "Pregabalin, Carbamazepine",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690341/download_qh9b22.jpg",
      description: "Gabapentin is used to treat nerve pain and seizures, and is often prescribed for conditions such as shingles or epilepsy."
    },
    {
      medid: 25,
      medname: "Omeprazole",
      brandname: "Prilosec",
      drug_category: "Gastrointestinal",
      store_name: "CVS Pharmacy",
      distance: 4.2,
      availability: true,
      home_delivery: true,
      price: 17.50,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "20mg",
      days_supply: 14,
      age_range: "12+ years",
      tags: "acid reflux, heartburn",
      alt_meds: "Pantoprazole, Lansoprazole",
      rating: 4.5,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690459/download_jihglo.jpg",
      description: "Omeprazole is a proton pump inhibitor used to treat acid reflux and other gastrointestinal issues like heartburn."
    },
    {
      medid: 28,
      medname: "Lisinopril",
      brandname: "Zestril",
      drug_category: "Cardiovascular",
      store_name: "CVS Pharmacy",
      distance: 5.0,
      availability: true,
      home_delivery: true,
      price: 9.50,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "hypertension, heart failure",
      alt_meds: "Enalapril, Ramipril",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690487/download_xesjje.jpg",
      description: "Lisinopril is used to treat high blood pressure and heart failure by relaxing blood vessels."
    },
    {
      medid: 3,
      medname: "Lipitor",
      brandname: "Pfizer",
      drug_category: "Cardiovascular",
      store_name: "Target Pharmacy",
      distance: 4.0,
      availability: true,
      home_delivery: false,
      price: 30.0,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "cholesterol reduction",
      alt_meds: "Atorvastatin, Simvastatin",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dzymyjltu/image/upload/v1731685309/lipitor_quwj3a.jpg",
      description: "Lipitor is a medication used to lower cholesterol and reduce the risk of heart disease."
    },
    {
      medid: 4,
      medname: "Zyrtec",
      brandname: "Johnson & Johnson",
      drug_category: "Antihistamine",
      store_name: "Walmart Pharmacy",
      distance: 2.0,
      availability: true,
      home_delivery: false,
      price: 10.50,
      tier: 1,
      generic: false,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "6+ years",
      tags: "allergy relief",
      alt_meds: "Claritin, Allegra",
      rating: 4.4,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690375/download_xm5msx.jpg",
      description: "Zyrtec is an antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes."
    },
    
    {
      medid: 6,
      medname: "Zyrtec",
      brandname: "Johnson & Johnson",
      drug_category: "Antihistamine",
      store_name: "Walgreens",
      distance: 5.0,
      availability: true,
      home_delivery: false,
      price: 14.00,
      tier: 1,
      generic: false,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "6+ years",
      tags: "allergy relief",
      alt_meds: "Claritin, Allegra",
      rating: 4.8,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690375/download_xm5msx.jpg",
      description: "Zyrtec is an antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itchy eyes."
    },
    
    {
      medid: 8,
      medname: "Xanax",
      brandname: "Pfizer",
      drug_category: "Psychiatry",
      store_name: "Walgreens",
      distance: 4.5,
      availability: true,
      home_delivery: false,
      price: 32.00,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "0.5mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "anxiety relief",
      alt_meds: "Lorazepam, Clonazepam",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690425/download_gx4fx0.jpg",
      description: "Xanax is used to treat anxiety and panic disorders by calming the nervous system."
    },
    {
      medid: 9,
      medname: "Xanax",
      brandname: "Pfizer",
      drug_category: "Psychiatry",
      store_name: "Target Pharmacy",
      distance: 2.8,
      availability: true,
      home_delivery: true,
      price: 29.75,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "0.5mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "anxiety relief",
      alt_meds: "Lorazepam, Clonazepam",
      rating: 4.9,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690425/download_gx4fx0.jpg",
      description: "Xanax is used to treat anxiety and panic disorders by calming the nervous system."
    },
    
    {
      medid: 11,
      medname: "Synthroid",
      brandname: "AbbVie",
      drug_category: "Endocrine",
      store_name: "CVS Pharmacy",
      distance: 3.5,
      availability: true,
      home_delivery: false,
      price: 21.00,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "50mcg",
      days_supply: 30,
      age_range: "12+ years",
      tags: "thyroid hormone replacement",
      alt_meds: "Levothyroxine, Euthyrox",
      rating: 4.8,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690060/download_mmm4ay.jpg",
      description: "Synthroid is used to treat hypothyroidism (low thyroid hormone levels) by providing synthetic thyroid hormone."
    },
    {
      medid: 12,
      medname: "Synthroid",
      brandname: "AbbVie",
      drug_category: "Endocrine",
      store_name: "Target Pharmacy",
      distance: 3.8,
      availability: true,
      home_delivery: true,
      price: 19.50,
      tier: 2,
      generic: true,
      dosage_form: "tablet",
      strength: "50mcg",
      days_supply: 30,
      age_range: "12+ years",
      tags: "thyroid hormone replacement",
      alt_meds: "Levothyroxine, Euthyrox",
      rating: 4.9,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690060/download_mmm4ay.jpg",
      description: "Synthroid is used to treat hypothyroidism (low thyroid hormone levels) by providing synthetic thyroid hormone."
    },    
    {
      medid: 14,
      medname: "Amoxicillin",
      brandname: "Mylan",
      drug_category: "Antibiotic",
      store_name: "CVS Pharmacy",
      distance: 1.5,
      availability: true,
      home_delivery: false,
      price: 16.00,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "500mg",
      days_supply: 10,
      age_range: "All ages",
      tags: "bacterial infections",
      alt_meds: "Penicillin, Cephalexin",
      rating: 4.5,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690099/download_n2zalx.jpg",
      description: "Amoxicillin is an antibiotic used to treat various bacterial infections such as ear infections, pneumonia, and strep throat."
    },
    {
      medid: 15,
      medname: "Amoxicillin",
      brandname: "Mylan",
      drug_category: "Antibiotic",
      store_name: "Target Pharmacy",
      distance: 2.2,
      availability: true,
      home_delivery: true,
      price: 14.00,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "500mg",
      days_supply: 10,
      age_range: "All ages",
      tags: "bacterial infections",
      alt_meds: "Penicillin, Cephalexin",
      rating: 4.8,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690099/download_n2zalx.jpg",
      description: "Amoxicillin is an antibiotic used to treat various bacterial infections such as ear infections, pneumonia, and strep throat."
    },
    
    {
      medid: 17,
      medname: "Metformin",
      brandname: "Bristol-Myers Squibb",
      drug_category: "Antidiabetic",
      store_name: "CVS Pharmacy",
      distance: 2.3,
      availability: true,
      home_delivery: false,
      price: 10.50,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "500mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "diabetes management",
      alt_meds: "Glipizide, Glyburide",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690236/download_saqb5g.jpg",
      description: "Metformin is used to manage blood sugar levels in people with type 2 diabetes and helps improve insulin sensitivity."
    },
    {
      medid: 18,
      medname: "Metformin",
      brandname: "Bristol-Myers Squibb",
      drug_category: "Antidiabetic",
      store_name: "Rite Aid Pharmacy",
      distance: 2.1,
      availability: true,
      home_delivery: true,
      price: 11.00,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "500mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "diabetes management",
      alt_meds: "Glipizide, Glyburide",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690236/download_saqb5g.jpg",
      description: "Metformin is used to manage blood sugar levels in people with type 2 diabetes and helps improve insulin sensitivity."
    },
    
    {
      medid: 20,
      medname: "Albuterol",
      brandname: "Ventolin",
      drug_category: "Respiratory",
      store_name: "CVS Pharmacy",
      distance: 0.8,
      availability: true,
      home_delivery: false,
      price: 34.50,
      tier: 2,
      generic: true,
      dosage_form: "inhaler",
      strength: "90mcg",
      days_supply: 30,
      age_range: "4+ years",
      tags: "asthma relief, bronchospasm",
      alt_meds: "Levalbuterol, Terbutaline",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690273/download_zkqrot.jpg",
      description: "Albuterol is a bronchodilator used to relieve bronchospasm in people with asthma and chronic obstructive pulmonary disease (COPD)."
    },
    {
      medid: 21,
      medname: "Albuterol",
      brandname: "Ventolin",
      drug_category: "Respiratory",
      store_name: "Rite Aid Pharmacy",
      distance: 1.4,
      availability: true,
      home_delivery: true,
      price: 33.00,
      tier: 2,
      generic: true,
      dosage_form: "inhaler",
      strength: "90mcg",
      days_supply: 30,
      age_range: "4+ years",
      tags: "asthma relief, bronchospasm",
      alt_meds: "Levalbuterol, Terbutaline",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690273/download_zkqrot.jpg",
      description: "Albuterol is a bronchodilator used to relieve bronchospasm in people with asthma and chronic obstructive pulmonary disease (COPD)."
    },
    
    {
      medid: 23,
      medname: "Gabapentin",
      brandname: "Neurontin",
      drug_category: "Neurology",
      store_name: "CVS Pharmacy",
      distance: 2.8,
      availability: true,
      home_delivery: true,
      price: 14.50,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "300mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "nerve pain, seizures",
      alt_meds: "Pregabalin, Carbamazepine",
      rating: 4.4,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690341/download_qh9b22.jpg",
      description: "Gabapentin is used to treat nerve pain and seizures, and is often prescribed for conditions such as shingles or epilepsy."
    },
    {
      medid: 24,
      medname: "Gabapentin",
      brandname: "Neurontin",
      drug_category: "Neurology",
      store_name: "Rite Aid Pharmacy",
      distance: 3.0,
      availability: true,
      home_delivery: true,
      price: 17.00,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "300mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "nerve pain, seizures",
      alt_meds: "Pregabalin, Carbamazepine",
      rating: 4.7,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690341/download_qh9b22.jpg",
      description: "Gabapentin is used to treat nerve pain and seizures, and is often prescribed for conditions such as shingles or epilepsy."
    },
    
    {
      medid: 26,
      medname: "Omeprazole",
      brandname: "Prilosec",
      drug_category: "Gastrointestinal",
      store_name: "Rite Aid Pharmacy",
      distance: 3.5,
      availability: true,
      home_delivery: false,
      price: 18.50,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "20mg",
      days_supply: 14,
      age_range: "12+ years",
      tags: "acid reflux, heartburn",
      alt_meds: "Pantoprazole, Lansoprazole",
      rating: 4.6,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690459/download_jihglo.jpg",
      description: "Omeprazole is a proton pump inhibitor used to treat acid reflux and other gastrointestinal issues like heartburn."
    },
    {
      medid: 27,
      medname: "Omeprazole",
      brandname: "Prilosec",
      drug_category: "Gastrointestinal",
      store_name: "Walmart Pharmacy",
      distance: 4.8,
      availability: true,
      home_delivery: true,
      price: 17.00,
      tier: 1,
      generic: true,
      dosage_form: "capsule",
      strength: "20mg",
      days_supply: 14,
      age_range: "12+ years",
      tags: "acid reflux, heartburn",
      alt_meds: "Pantoprazole, Lansoprazole",
      rating: 4.8,
      pxreq: false,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690459/download_jihglo.jpg",
      description: "Omeprazole is a proton pump inhibitor used to treat acid reflux and other gastrointestinal issues like heartburn."
    },
    {
      medid: 29,
      medname: "Lisinopril",
      brandname: "Zestril",
      drug_category: "Cardiovascular",
      store_name: "Walmart Pharmacy",
      distance: 4.8,
      availability: true,
      home_delivery: true,
      price: 9.75,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "hypertension, heart failure",
      alt_meds: "Enalapril, Ramipril",
      rating: 4.8,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690487/download_xesjje.jpg",
      description: "Lisinopril is used to treat high blood pressure and heart failure by relaxing blood vessels."
    },
    {
      medid: 30,
      medname: "Lisinopril",
      brandname: "Zestril",
      drug_category: "Cardiovascular",
      store_name: "Walgreens",
      distance: 4.2,
      availability: true,
      home_delivery: false,
      price: 10.25,
      tier: 1,
      generic: true,
      dosage_form: "tablet",
      strength: "10mg",
      days_supply: 30,
      age_range: "18+ years",
      tags: "hypertension, heart failure",
      alt_meds: "Enalapril, Ramipril",
      rating: 4.6,
      pxreq: true,
      addToCart: false,
      image: "https://res.cloudinary.com/dnw6exszc/image/upload/v1731690487/download_xesjje.jpg",
      description: "Lisinopril is used to treat high blood pressure and heart failure by relaxing blood vessels."
    }
  ]);

  const toggleAddToCart = (medid) => {
    setAllDrugs((prevDrugs) =>
      prevDrugs.map((drug) =>
        drug.medid === medid ? { ...drug, addToCart: !drug.addToCart } : drug
      )
    );
  };

  return (
    <DrugsContext.Provider value={{ allDrugs, setAllDrugs ,toggleAddToCart }}>
      {children}
    </DrugsContext.Provider>
  );
};

export const useDrugsContext = () => useContext(DrugsContext);